tasks:
  - prepare_dataset
  - train_model

model_name: yolo11n.pt
epochs: 3
image_size: 512
batch_size: 4
num_workers: 18
device: "1" # TODO: implement GPUtils for automatic selection of GPUs

random_seed: 42
validation_split: 0.2
parallel: true
parallel_workers: 16

prepare_dataset:
  remove_after_split: false # removes images and annotations after creating train/val/test splits
  ignore_non_targets: true # filters annotations to ignore non-targets
 
train_from_checkpoint: true
