name: semif_plantdet
channels:
  - conda-forge
  - defaults
dependencies:
  - python==3.11
  - pip
  - hydra-core
  - omegaconf
  - pandas
  - numpy
  - sqlite
  - cvat-sdk
  - opencv
  # - matplotlib
  # - seaborn
  # - scikit-learn