tasks:
  - evaluate_model
  # - benchmark_nms
  # - visualize_nms
  - new_ms_inferencing

split: test #val
save_json: true
run_version: 1 # looks in runs_1; is ignored if custom_path is provided
custom_path: /home/ajajoo3/SemiF-PlantDetection/new_training_best.pt # Provide a custom model path, if provided, ignores run_version

conf: 0.35
iou: 0.65
scales: [0.15, 0.25, 0.5, 1, 1.5] # multiscale inference scales

gpus:
  n: 4          # number of GPUs to use
  exclude_id: 0 # skip first GPU

nms_method: ultralytics
