defaults:
  - database: training_dataset
  - paths: default
  - _self_
  - preprocess: default
  - train: default
# each mode is a pipeline mode
# preprocess/train
# list of tasks available in mode specific config
mode: preprocess

project:
  name: anuraag_test

# used mainly in download_images
images:
  output_path: ${paths.preprocess.image_dir}
  parallel: true
  parallel_workers: 16

# used mainly in cvat_formatter and cvat_importer
cvat:
  output_path: ${paths.data_dir}/cvat_dataset
  default_image_width: 9560
  default_image_height: 6368
  resize_factor: 0.75
  parallel: true
  parallel_workers: 16
  class_mapping:
    plant: 0
    non_target: 1
    color_checker: 2
  dataset_format: "Ultralytics YOLO Detection 1.0"

# configure credentials
secrets_path: ${paths.secrets_dir}/default.yaml
