defaults:
  - database: default
  - paths: default
  - _self_
  - preprocess: default
  - export: default
  - train: default

# each mode is a pipeline mode
# preprocess/train/export
# list of tasks available in mode specific config
mode: train

# used to reference project and task in CVAT
project:
  name: anuraag_new_test_3
  task_name: train

# used mainly in download_images
images:
  parallel: true
  parallel_workers: 16

# used mainly in cvat_formatter and cvat_importer
cvat:
  default_image_width: 9560
  default_image_height: 6368
  resize_factor: 0.75
  parallel: true
  parallel_workers: 16
  dataset_format: "Ultralytics YOLO Detection 1.0"

