# path to root directory
# this relies on main.py to be run from the project root
root_dir: ${hydra:runtime.cwd}

# path to data directory
data_dir: ${paths.root_dir}/data/

# project dir path (project.name from config.yaml)
project_dir: ${paths.root_dir}/projects/${project.name}

# path to logging directory
log_dir: ${paths.root_dir}/logs/

# preprocess output paths
preprocess:
  csv_dir: ${paths.project_dir}/preprocess/data/data_csvs
  image_dir: ${paths.project_dir}/preprocess/data/images
  model_data_dir: ${paths.project_dir}/preprocess/data/model_data

# training output paths
train:
  output_dir: ${paths.project_dir}/train

# path to database
db_path: ${paths.data_dir}/db/agir.db

# path to secrets directory
secrets_dir: ${paths.root_dir}/secrets/

lts_locations:
  # - /Volumes/screberg/longterm_images
  # - /Volumes/screberg/GROW_DATA
  # - /Volumes/screberg/longterm_images2
  - /mnt/research-projects/s/screberg/longterm_images
  - /mnt/research-projects/s/screberg/GROW_DATA
  - /mnt/research-projects/s/screberg/longterm_images2

lts_human_annotations:
  # - /Volumes/screberg/longterm_images2/semifield-database/plant-detection/annotations/
  - /mnt/research-projects/s/screberg/longterm_images2/semifield-database/plant-detection/annotations/
