# path to root directory
# this relies on main.py to be run from the project root
root_dir: ${hydra:runtime.cwd}

# path to data directory
data_dir: ${paths.root_dir}/data/

# project dir path (project.name from config.yaml)
project_dir: ${paths.root_dir}/projects/${project.name}/${project.task_name}

# path to logging directory
log_dir: ${paths.root_dir}/logs/

# preprocess output paths
preprocess:
  csv_dir: ${paths.project_dir}/preprocess/data_csvs
  image_dir: ${paths.project_dir}/preprocess/images
  cvat_output: ${paths.project_dir}/cvat_dataset
  label_dir: ${paths.project_dir}/preprocess/annotations

# training output paths
train:
  model_dir: ${paths.project_dir}/train/models
  model_data_dir: ${paths.project_dir}/train/data
  checkpoint: 

# evaluation output paths
evaluate:
  data_yaml: ${paths.train.model_data_dir}/data.yaml
  save_dir: ${paths.project_dir}/evaluate

# path to database
db_path: ${paths.data_dir}/db/agir.db

# path to secrets directory
secrets: ${paths.root_dir}/secrets/default.yaml

lts_locations:
  - /mnt/research-projects/s/screberg/longterm_images
  - /mnt/research-projects/s/screberg/GROW_DATA
  - /mnt/research-projects/s/screberg/longterm_images2

# lts_human_annotations: /mnt/research-projects/s/screberg/longterm_images2/semifield-database/plant-detection/annotations/
lts_human_annotations: ${paths.root_dir}/temp_lts_human_annotations
